"""Variants (IMPLEMENTATION_PLAN.md §12): typed edit vocabulary, expansion,
lineage. Depends on ``model`` only (plan §5.3 rule 2); wire documents and
fingerprints arrive as data from ``app``."""

from configbuilder.variants.edits import (
    EDIT_CLASSES,
    AddLinkage,
    AddModification,
    AddRecord,
    EditError,
    RemoveLinkage,
    RemoveModification,
    RemoveRecord,
    SetAlignment,
    SetComponentDefinition,
    SetComponentRepresentation,
    SetComponentCount,
    SetDescription,
    SetFormatTarget,
    SetJobDescription,
    SetName,
    SetReferences,
    SetSeeds,
    SetSequence,
    SetSingleAlignment,
    apply_edit,
    describe_edit,
    record_for_key,
)
from configbuilder.variants.expansion import expand
from configbuilder.variants.spec import (
    Lineage,
    Variant,
    VariantSpec,
    VariantSpecError,
    declared_changes,
)

__all__ = [
    "EDIT_CLASSES",
    "AddLinkage",
    "AddModification",
    "AddRecord",
    "EditError",
    "Lineage",
    "RemoveLinkage",
    "RemoveModification",
    "RemoveRecord",
    "SetAlignment",
    "SetComponentDefinition",
    "SetComponentRepresentation",
    "SetComponentCount",
    "SetDescription",
    "SetFormatTarget",
    "SetJobDescription",
    "SetName",
    "SetReferences",
    "SetSeeds",
    "SetSequence",
    "SetSingleAlignment",
    "Variant",
    "VariantSpec",
    "VariantSpecError",
    "apply_edit",
    "declared_changes",
    "describe_edit",
    "expand",
    "record_for_key",
]
